#! /bin/sh

### BEGIN INIT INFO
# Provides:          foodzilla-backend
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Foodzilla Backend
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Foodzilla Backend"
    sudo /home/<username>/start.sh
    ;;
  stop)
    echo "Stopping Foodzilla Backend"
    sudo /home/<username>/stop.sh
    ;;
  *)
    echo "Usage: /etc/init.d/foodzilla-backend {start|stop}"
    exit 1
    ;;
esac

exit 0

